steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - gc-cloud-build
  - --region=us-east1
  - --source=.
  - --allow-unauthenticated
  - --trigger-http
  - --runtime=python311
  - --project=projeto-estudos-415711
  - --entry-point=hello_world